---

-

  hosts: worker

  vars:
    motd_centos: "welcome to ansible metlife"
    motd_ubuntu: "Welcome to ubuntu machine"

  tasks:
    - name: configure an Motd(message of the day)
      copy:
        content: "{{ motd_centos }}"
        dest: /etc/motd
      notify: MOTD Changed
      when: ansible_distribution == "CentOS"
      
    - name: configure an Motd(message of the day)
      copy:
        content: "{{ motd_ubuntu }}"
        dest: /etc/motd
      notify: MOTD Changed
      when: ansible_distribution == "Ubuntu"

  handlers:
    - name: MOTD Changed
      debug:
        msg: The Motd has changed
